# Generated by Django 4.2.16 on 2024-09-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
